# Module: NumPy Assignments
## Lesson: NumPy


In [1]:
print('hello World')

hello World


 ### Assignment 1: Array Creation and Manipulation
 1.Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

In [13]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
print(np.ndim(arr))
arr.shape
third_col=arr[:,2:3]
print('third_col',third_col)
arr[:,2:3]=1
print('new array',arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
third_col [[ 3]
 [ 8]
 [13]]
new array [[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [17]:
random_matrix=np.random.randint(1,21,size=(5,5))
print(random_matrix)
diag=random_matrix.diagonal()
print('\n',diag)
np.fill_diagonal(random_matrix,0)
print(random_matrix)

[[ 7 15 12  7 18]
 [ 7 13  3 11 15]
 [ 9  9  2  5 20]
 [ 7 18 16 15 10]
 [14  8  3  7  5]]

 [ 7 13  2 15  5]
[[ 0 15 12  7 18]
 [ 7  0  3 11 15]
 [ 9  9  0  5 20]
 [ 7 18 16  0 10]
 [14  8  3  7  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [19]:
random_matrix=np.random.randint(1,37,size=(6,6))
print(random_matrix)
sub_array=random_matrix[2:5,1:4]
print(sub_array)

[[26 16 12 23  1  1]
 [15 14 31 21 15 13]
 [ 8 25  8 32  2  9]
 [24 35 12 17 27 35]
 [24 20 10 22 18  3]
 [25 11  4 12 23 28]]
[[25  8 32]
 [35 12 17]
 [20 10 22]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [20]:
matrix_for_border=np.random.randint(1,16,size=(5,5))
print(matrix_for_border)


top=matrix_for_border[0,:]
bottom=matrix_for_border[-1,:]
right=matrix_for_border[:,-1]
left=matrix_for_border[:,0]

border_element=np.concatenate([top,left[::-1],right,bottom[::-1]])

print(border_element)

[[ 1 12  3  2  5]
 [13 14 11 15 15]
 [11 14 13 15 10]
 [12  7  2  8  6]
 [15  6 12  1  1]]
[ 1 12  3  2  5 15 12 11 13  1  5 15 10  6  1  1  1 12  6 15]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [23]:
arr1=np.random.randint(1,11,size=(3,4))
arr2=np.random.randint(11,21,size=(3,4))

print(arr1,'\n',arr2)

print("Addition:", arr1+arr2)
print("Substruction:", arr1-arr2)
print("Multiplication:", arr1 * arr2)
div_res=arr1 / arr2
print("Division:",np.round(div_res,2))


[[10  7  5 10]
 [ 9  8  8  2]
 [10  6  3  4]] 
 [[13 19 19 11]
 [14 17 11 14]
 [13 17 19 18]]
Addition: [[23 26 24 21]
 [23 25 19 16]
 [23 23 22 22]]
Substruction: [[ -3 -12 -14  -1]
 [ -5  -9  -3 -12]
 [ -3 -11 -16 -14]]
Multiplication: [[130 133  95 110]
 [126 136  88  28]
 [130 102  57  72]]
Division: [[0.77 0.37 0.26 0.91]
 [0.64 0.47 0.73 0.14]
 [0.77 0.35 0.16 0.22]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [25]:
arr=np.random.randint(1,16,size=(4,4))
print(arr)

print('row wise addition',np.sum(arr,axis=1))
print('col wise addition',np.sum(arr,axis=0))

[[11  1 10 14]
 [ 4 13  3 11]
 [ 4 12  6  5]
 [10  7 15  5]]
row wise addition [36 31 27 37]
col wise addition [29 33 34 35]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [ ]:

arr=np.random.randint(1,26,size=(5,5))
print(arr)
print(np.ndim(arr))
mean=np.mean(arr)
print(mean)
std=np.std(arr)
median=np.median(arr)
print(median)
print(std.round(2))
variance=np.var(arr)
print(variance.round(2))


[[18 13  9 20  7]
 [ 1 11  4 14 25]
 [16 17 13 14 18]
 [ 2 18  1 19  6]
 [25 13 17 16 24]]
2
13.64
14.0
6.94
48.23
[[ 0.628 -0.092 -0.668  0.916 -0.956]
 [-1.82  -0.38  -1.388  0.052  1.636]
 [ 0.34   0.484 -0.092  0.052  0.628]
 [-1.676  0.628 -1.82   0.772 -1.1  ]
 [ 1.636 -0.092  0.484  0.34   1.492]]


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [35]:

arr=np.random.randint(1,10,size=(3,3))
print(arr)
normalized=(arr-mean)/std
print(normalized.round(3))

[[9 3 7]
 [3 7 7]
 [3 5 7]]
[[-0.668 -1.532 -0.956]
 [-1.532 -0.956 -0.956]
 [-1.532 -1.244 -0.956]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [33]:
arr=np.array([[1,2,3],[3,4,5]])
print(arr)
arr2=np.array([10,20,30])
print(arr+arr2)

[[1 2 3]
 [3 4 5]]
[[11 22 33]
 [13 24 35]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [36]:
arr=np.array([[1,2,3],[3,4,5]])
print(arr)
arr2=np.array([10,20,30])
print(arr-arr2)

[[1 2 3]
 [3 4 5]]
[[ -9 -18 -27]
 [ -7 -16 -25]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [82]:
A = np.array([[4, 2, 1],
              [3, 5, 7],
              [1, 1, 2]])

det=np.linalg.det(A)
inverse=np.linalg.inv(A)
eigenValue=np.linalg.eigvals(A)

print(f"Det:{det:.2f}\n inverse: \n{inverse.round(2)} \n eigenValue:{eigenValue.round(2)}")



Det:12.00
 inverse: 
[[ 0.25 -0.25  0.75]
 [ 0.08  0.58 -2.08]
 [-0.17 -0.17  1.17]] 
 eigenValue:[8.27 2.   0.73]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [84]:
arr1=np.random.randint(1,15,size=(2,3))
arr2=np.random.randint(1,15,size=(3,2))
mul=np.dot(arr1,arr2)
print(mul)

[[233  81]
 [126  41]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [85]:

arr=np.random.randint(1,10,size=(3,3))
print(arr)
print(arr.shape)
reshape_arr=arr.reshape (1,9)
print(reshape_arr.shape)
print(np.ndim(reshape_arr))
again_reshape=reshape_arr.reshape(9,1)
print(again_reshape)


[[1 1 3]
 [9 6 1]
 [2 9 5]]
(3, 3)
(1, 9)
2
[[1]
 [1]
 [3]
 [9]
 [6]
 [1]
 [2]
 [9]
 [5]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [88]:
arr=np.random.randint(1,10,size=(5,5))
print(arr)

flatten_arr=arr.flatten()
print('Flatten array: ',flatten_arr)

return_arr=flatten_arr.reshape(5,5)
print("return array as 5*5:",return_arr)


[[9 5 1 2 4]
 [6 5 9 6 9]
 [3 1 8 4 9]
 [4 3 3 1 3]
 [6 1 6 7 4]]
Flatten array:  [9 5 1 2 4 6 5 9 6 9 3 1 8 4 9 4 3 3 1 3 6 1 6 7 4]
return array as 5*5: [[9 5 1 2 4]
 [6 5 9 6 9]
 [3 1 8 4 9]
 [4 3 3 1 3]
 [6 1 6 7 4]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [89]:
arr = np.random.randint(1, 101, size=(5, 5))
print("Original Array:\n", arr)

corner_rows=[0,0,4,4]
corner_colms=[0,4,0,4]

corners=arr[corner_rows,corner_colms]

print(corners)

Original Array:
 [[96  3 16 40 60]
 [ 7 76 43 16 51]
 [18 75 74 26 95]
 [74 53 48 98 42]
 [52 31 80 66 27]]
[96 60 52 27]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [91]:
arr = np.random.randint(1, 101, size=(4, 4))

print('orginaal array ',arr)

arr[arr>10]=10
print(arr)


orginaal array  [[22 91 99 74]
 [13 92 45 87]
 [88 25 58 79]
 [67  9 69  1]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10  9 10  1]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [94]:
dtype = [('name', 'U10'),   
         ('age', 'i4'),    
         ('weight', 'f4')]  

data=np.array([ ('Alice', 25, 68.5),
    ('Bob', 22, 75.0),
    ('Charlie', 30, 80.2),
    ('Diana', 28, 55.0)],dtype= dtype)

print("Original array:")
print(data)

sorted_data=np.sort(data,order='age')
print("\nSorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 68.5) ('Bob', 22, 75. ) ('Charlie', 30, 80.2)
 ('Diana', 28, 55. )]

Sorted array by age:
[('Bob', 22, 75. ) ('Alice', 25, 68.5) ('Diana', 28, 55. )
 ('Charlie', 30, 80.2)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [95]:
dtype = [('x', 'i4'), ('y', 'i4')]

points = np.array([
    (1, 2),
    (4, 6),
    (5, 1),
    (7, 8)
], dtype=dtype)

print("Points:")
print(points)

# Step 2: Extract x and y as separate arrays for vectorized operations
x = points['x']
y = points['y']

# Compute distance matrix using broadcasting
dx = x[:, np.newaxis] - x[np.newaxis, :]
dy = y[:, np.newaxis] - y[np.newaxis, :]
dist_matrix = np.sqrt(dx**2 + dy**2)

print("\nEuclidean distance matrix:")
print(np.round(dist_matrix, 2))

Points:
[(1, 2) (4, 6) (5, 1) (7, 8)]

Euclidean distance matrix:
[[0.   5.   4.12 8.49]
 [5.   0.   5.1  3.61]
 [4.12 5.1  0.   7.28]
 [8.49 3.61 7.28 0.  ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [99]:
import numpy.ma as ma
arr = np.random.randint(1, 21, size=(4, 4))
masked_array=ma.masked_greater(arr,10)
print("\nMasked Array (elements > 10 are masked):\n", masked_array)
mean=masked_array.mean()
print(mean)

fill_mask=masked_array.filled(mean)
print("\nMasked Array with mean:\n", fill_mask)



Masked Array (elements > 10 are masked):
 [[10 -- -- --]
 [-- 3 -- 6]
 [-- 3 -- --]
 [3 -- -- 8]]
5.5

Masked Array with mean:
 [[10  5  5  5]
 [ 5  3  5  6]
 [ 5  3  5  5]
 [ 3  5  5  8]]


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [100]:

arr = np.array([1, 2, 3, -1, 5])
masked_arr =ma.masked_less(arr,0) 

print(masked_arr)
print(masked_arr.mean())

[1 2 3 -- 5]
2.75
